when:
  - event: [push, manual]
    branch: main

steps:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64
      repo: openuem/openuem-console
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
