when:
  - event: push
    branch: main

steps:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64
      tag: v0.1.0
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
