steps:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64
      tag: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
